### ISSUE TITLE
Two issues with the build

### ISSUE THREAD

**Issue by Fil** [unkleho/d3-render#1]
1. I couldn't find how to load this with observable's `require()`, and had to run it through a local instance of packd to get a usable format.
2. the package exports two methods called `default` and `renderSelection`; not sure what `default` is for, and I would expect to have `render`.

https://observablehq.com/d/6f1627b8f1f3d109

**Comment by Fil** [comment]
I see you solved (1) at https://observablehq.com/@unkleho/hello-d3-render ; ideally it would just be "d3-render" but it's quite usable already (as an aside, I had tried this file, but forgot to remove the /browse/ part from https://unpkg.com/browse/d3-render@0.1.4/dist/d3-render.umd.production.min.js ! 🙄  ).

**Comment by unkleho** [comment]
Hi Fil,

1. I've just updated the package.json to have an explicit reference for unpkg to the UMD build. It should work in observable now without the crazy link!
![image](https://user-images.githubusercontent.com/1124027/80602632-b5400d00-8a72-11ea-9ae9-926e288e245f.png)

2. As a total newbie to building for the D3 ecosystem, i didn't read up on best practises. I may rethink how I'm exporting the package. `default` is the full `render` function, which can actually be named anything when imported.

**Comment by Fil** [comment]
Great! I can't help you with the exports, the only thing I do for my own module is to copy from one of @mbostock's modules ;-)
