### ISSUE TITLE
Proper way to avoid kebab-case translation?

### ISSUE THREAD

**Issue by emrul** [unkleho/d3-render#6]
Hi,

I see that d3Render changes camel-case in JavaScript to kebab-case.  I am wondering how I should specify properties like markerHeight that must appear as a camel-case attribute in the SVG?

Ref: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/markerHeight

Thanks!

**Comment by unkleho** [comment]
Hi emrul,

Right now, **all** attributes are converted from camel case to kebab case.

I totally forgot about real camel case attributes! Probably the easiest thing is to have a list to check before camel->kebab conversion.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute has a list I could work off.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes doesn't seem to have any camel case attributes (makes my job easier)

Thanks for letting me know.

**Comment by unkleho** [comment]
Hi emrul,

Should be fixed in v0.2.5
https://github.com/unkleho/d3-render/blob/v0.2.5/src/render.ts#L325
