### ISSUE TITLE
How to draw an axis...

### ISSUE THREAD

**Issue by CobusT** [unkleho/d3-render#9]
I was trying to use render to draw an axis, but I must be doing something wrong.

How do I translate this to a declarative object that I can render:
```  
svg.append("g")
    .attr("transform", `translate(${margin.left},0)`)
    .call(d3.axisLeft(y))
    .append("text")
    .attr("style", `fill:black; font-weight: 700; font-size: 12px`)
    .attr("text-anchor", "middle")
    .attr("transform",`translate(-35,${(height-margin.bottom-margin.top)/2 + margin.top}),rotate(-90)`)
    .text("Month");
```

I tried this:

```
 {
    append: "g",
    transform: `translate(${margin.left},0)`,
    call: d3.axisLeft(y)
  }
```

But I get an error. Any help would be appreciated. I think I will find d3-render very useful, but am obviously missing a few concepts.

**Comment by unkleho** [comment]
Perhaps this example may help?
https://github.com/unkleho/d3-render/blob/master/example/bar-chart.ts#L57

**Comment by CobusT** [comment]
Hi.
~~I still cannot get it to work. I must be doing something wrong! Is there any way you can have a quick look at this notebook?~~
https://observablehq.com/d/4bb6c8c31f9a529c

I was using render imported from this notebook: 
https://observablehq.com/@unkleho/introducing-d3-render-truly-declarative-and-reusable-d3?collection=@unkleho/d3-render

I changed to this instead:
`render = (await require('d3-render@0.3.0/dist/d3-render.umd.development.js')).default`

and now it works!
I think you can close this now.

**Comment by unkleho** [comment]
Fantastic. Sorry I meant to look at the notebook, but glad you got it working in the end.
